const data = {
  products: [
    {
      name: 'Toitures',
      slug: 'Contruction, rénovation et couverture de toit',
      category: 'Travaux',
      image: '/images/toiture1.jpeg',
      image2: '/images/toiture2.jpeg',
      price: 70,
      brand: 'Toitures',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "La construction, la rénovation et la couverture de toit sont des éléments essentiels dans le domaine de la construction et de l'entretien des bâtiments. Voici quelques informations générales sur chacun de ces aspects :",
      titre1: "Construction de toit",
      li1: "La construction de toit est le processus de création d'une structure de toit sur un bâtiment nouvellement construit. Cela peut inclure la conception du toit, le choix des matériaux, la pose des poutres ou des fermes, et la mise en place de la couverture extérieure.",
      li2: "Les toits peuvent être construits dans une variété de styles, notamment en pente (toit en pente) ou plat, en fonction des besoins esthétiques et structurels du bâtiment.",
      li3: "La construction d'un toit doit respecter les codes du bâtiment locaux et nationaux, ainsi que les normes de sécurité.",
      titre2: "Rénovation de toit",
      li4: "La rénovation de toit consiste à réparer ou à améliorer un toit existant. Cela peut être nécessaire en raison de l'usure naturelle, de dommages causés par des intempéries ou d'une mise à niveau esthétique.",
      li5: "Les rénovations de toit peuvent inclure le remplacement de matériaux de couverture, la réparation de fuites, le renforcement de la structure du toit, l'ajout d'isolation, ou des améliorations pour améliorer l'efficacité énergétique.",
      li6: "La rénovation de toit est importante pour prolonger la durée de vie du toit et maintenir l'intégrité de la structure du bâtiment.",
      titre3: "Couverture de toit",
      li7: "La couverture de toit fait référence aux matériaux utilisés pour recouvrir la surface du toit, les protégeant des éléments et des intempéries.",
      li8: "Les matériaux de couverture de toit les plus courants comprennent les tuiles, les bardeaux, le métal, le chaume, le bois et le revêtement de toit plat en membrane d'étanchéité.",
      li9: "Le choix du matériau de couverture dépend de divers facteurs, tels que le climat local, le style architectural, le budget et les préférences esthétiques.",
      text: "Lorsque vous envisagez des travaux de construction, de rénovation ou de couverture de toit, il est important de faire appel à des professionnels qualifiés, tels que des entrepreneurs en construction, des couvreurs ou des artisans du bâtiment, pour s'assurer que les travaux sont effectués correctement et conformément aux réglementations locales."
    },
    {
      name: 'Ossatures bois',
      slug: 'Contruction, rénovation et extension',
      category: 'Travaux',
      image: '/images/ossature1.jpeg',
      image2: '/images/ossature2.jpeg',
      price: 80,
      brand: 'Charpentes',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "Une entreprise de construction, de rénovation et de couverture de toit est spécialisée dans la planification, la réalisation et la rénovation de projets de construction, tout en offrant des services liés à la toiture. Voici un aperçu des services et des activités qu'une telle entreprise peut proposer :",
      titre1: "Construction",
      li1: "Nouvelle construction : Conception et construction de bâtiments neufs, qu'il s'agisse de projets résidentiels, commerciaux, industriels ou institutionnels.",
      li2: "Gestion de projet : Gestion complète du processus de construction, de la planification initiale à la livraison finale du projet.",
      li3: "",
      titre2: "Rénovation",
      li4: "Rénovation intérieure : Remise à neuf des espaces intérieurs, y compris la rénovation de cuisines, de salles de bains, de sous-sols et de toutes les autres pièces.",
      li5: "Rénovation extérieure : Amélioration de l'aspect extérieur des bâtiments, y compris la rénovation des façades, des terrasses, des jardins, etc.",
      li6: "",
      titre3: "Couverture de toit",
      li7: "Réparation de toiture : Réparation des dommages, des fuites et de l'usure de la toiture.",
      li8: "Remplacement de toiture : Installation de nouvelles toitures pour remplacer celles qui sont trop anciennes ou gravement endommagées.",
      li9: "Installation de revêtements de toit : Pose de différents types de matériaux de couverture, tels que le bardeau, l'ardoise, le métal, etc.",
      text: "Il est essentiel de choisir une entreprise de construction, de rénovation et de couverture de toit réputée et expérimentée pour garantir que vos projets sont menés à bien de manière efficace, dans les délais et conformément aux normes de qualité. Avant de prendre une décision, il est recommandé de demander des recommandations, de consulter des avis et d'obtenir plusieurs devis pour comparer les offres. Assurez-vous également que l'entreprise est correctement assurée pour couvrir tout dommage éventuel."
    },
    {
      name: 'Ossatures métallique',
      slug: 'Contruction, rénovation et extension métallique',
      category: 'Travaux',
      image: '/images/ossaturemetallique.jpg',
      image2: '/images/ossaturemetallique.jpg',
      price: 80,
      brand: 'Ossatures métallique',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "Une entreprise de construction, de rénovation et d'extension est une entreprise spécialisée dans la planification, la conception et la réalisation de projets de construction, de rénovation et d'agrandissement de bâtiments. Voici un aperçu des services et des activités qu'une telle entreprise peut proposer :",
      titre1: "Construction",
      li1: "Nouvelle construction : Conception et construction de bâtiments neufs, qu'il s'agisse de projets résidentiels, commerciaux, industriels ou institutionnels.",
      li2: "Gestion de projet : Gestion complète du processus de construction, de la planification initiale à la livraison finale du projet.",
      titre2: "Rénovation",
      li4: "Rénovation intérieure : Remise à neuf des espaces intérieurs, y compris la rénovation de cuisines, de salles de bains, de sous-sols et de toutes les autres pièces.",
      li5: "Rénovation extérieure : Amélioration de l'aspect extérieur des bâtiments, y compris la rénovation des façades, des terrasses, des jardins, etc.",
      li6: "",
      titre3: "Extension",
      li7: "Agrandissement de bâtiments existants : Conception et construction d'extensions pour augmenter l'espace habitable ou fonctionnel d'un bâtiment.",
      li8: "Surélévation : Ajout d'étages supplémentaires sur un bâtiment existant pour créer plus d'espace.",
      li9: "",
      text: "Il est essentiel de choisir une entreprise de construction, de rénovation et d'extension réputée et expérimentée pour garantir que vos projets de construction sont menés à bien de manière efficace, dans les délais et conformément aux normes de qualité. Avant de prendre une décision, il est recommandé de demander des recommandations, de consulter des avis et d'obtenir plusieurs devis pour comparer les offres. Assurez-vous également que l'entreprise est correctement assurée pour couvrir tout dommage éventuel."
    },
    {
      name: 'Isolation',
      slug: 'Toitures et façades',
      category: 'Travaux',
      image: '/images/isolation1.jpeg',
      image2: '/images/isolation2.jpeg',
      price: 90,
      brand: 'Isolation',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "Une entreprise spécialisée dans la construction, la rénovation et l'extension métallique offre des services liés à l'utilisation du métal dans la construction, la rénovation et l'agrandissement de bâtiments et de structures. Voici un aperçu des services et des activités que ce type d'entreprise peut fournir :",
      titre1: "Construction métallique",
      li1: "Construction de bâtiments métalliques : Conception et construction de bâtiments industriels, commerciaux ou résidentiels en utilisant des charpentes métalliques.",
      li2: "Assemblage de structures en acier : Installation de poutres, de colonnes et d'autres éléments de support en acier pour créer des structures solides.",
      li3: "",
      titre2: "Rénovation métallique",
      li4: "Rénovation de bâtiments métalliques existants : Modernisation de bâtiments anciens en remplaçant des éléments métalliques usés ou en améliorant l'isolation thermique et acoustique.",
      li5: "Restauration de façades métalliques : Réparation ou rénovation des façades en métal pour améliorer leur aspect esthétique et leur fonctionnalité.",
      li6: "",
      titre3: "Extension métallique",
      li8: "Extension de bâtiments existants : Ajout de nouveaux espaces ou de nouvelles sections à des bâtiments existants en utilisant des structures métalliques pour créer des extensions durables et fonctionnelles.",
      li9: "",
      text: "Le choix d'une entreprise de construction, de rénovation et d'extension métallique réputée et expérimentée est essentiel pour garantir la qualité et la durabilité des travaux métalliques sur votre bâtiment. Avant de prendre une décision, il est recommandé de demander des recommandations, de consulter des avis et d'obtenir plusieurs devis pour comparer les offres. Assurez-vous également que l'entreprise est correctement assurée pour couvrir tout dommage éventuel."
      },
    // {
    //   name: "Charpentes",
    //   slug: 'Traditionnelles et préfabriquées',
    //   category: 'Travaux',
    //   image: '/images/charpente1.jpeg',
    //   image2: '/images/charpente2.jpeg',
    //   price: 90,
    //   brand: 'Charpentes',
    //   rating: 2.9,
    //   numReviews: 13,
    //   countInStock: 20,
    //   description: "L’équipe de Toitures Bertrand se déplace dans le Brabant Wallon, à Bruxelles et dans un rayon de 40km pour l’installation de vos charpentes traditionnelles ou charpentes préfabriquées pour toitures plates et en pente. Forts de plus de 20 ans d’expérience, nous concevons également vos extensions et rehaussons vos bâtiments.",
    // },
    {
      name: "Charpentes",
      slug: 'Toitures et fondations',
      category: 'Travaux',
      image: '/images/charpente1.jpeg',
      image2: '/images/charpente2.jpeg',
      price: 90,
      brand: 'Charpentes',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Une entreprise de toitures et de fondations est une entreprise spécialisée dans la construction, la réparation, la rénovation, et l'entretien des toits et des fondations des bâtiments. Ces deux éléments sont essentiels pour assurer la stabilité, la durabilité et la protection d'une structure. Voici un aperçu des services et des activités que ce type d'entreprise peut offrir :",
      titre1: "Services de toiture",
      li1: "Réparation de toiture : Réparation des dommages causés par des intempéries, des fuites, des problèmes d'isolation, etc.",
      li2: "Remplacement de toiture : Installation de nouvelles toitures pour remplacer celles qui sont trop anciennes ou gravement endommagées.",
      li3: "Nettoyage de toiture : Élimination de la saleté, de la mousse, et des débris pour prolonger la durée de vie de la toiture.",
      titre2: "Services de fondations",
      li4: "Réparation de fondations : Correction des problèmes tels que les fissures, l'instabilité ou l'affaissement de la fondation.",
      li5: "Étanchéité de fondation : Application de matériaux d'étanchéité pour prévenir les infiltrations d'eau dans la fondation.",
      li6: "Renforcement de fondation : Renforcement de la fondation pour augmenter sa résistance structurelle.",
      titre3: "Conformité aux normes et réglementations ",
      li7: "L'entreprise de toitures et de fondations doit respecter les normes de construction locales et nationales pour garantir la qualité et la sécurité des travaux.",
      li8: "",
      li9: "",
      text: "Le choix d'une entreprise de toitures et de fondations expérimentée et réputée est essentiel pour garantir la stabilité et la durabilité de votre propriété. N'hésitez pas à demander des recommandations, à consulter des avis, et à obtenir plusieurs devis avant de prendre une décision. Assurez-vous également que l'entreprise est correctement assurée pour couvrir tout dommage potentiel."
    },
    {
      name: "Bétons",
      slug: 'bétons',
      category: 'Travaux',
      image: '/images/beton.jpg',
      image2: '/images/beton.jpg',
      price: 90,
      brand: 'Bétons',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Une entreprise de béton est une société spécialisée dans la production, la livraison et l'installation de béton, ainsi que dans la réalisation de divers projets de construction et de génie civil nécessitant l'utilisation de béton. Voici un aperçu des services et des activités qu'une entreprise de béton peut offrir :",
      titre1: "Production de béton",
      li1: "Les entreprises de béton disposent d'installations de mélange où elles produisent du béton prêt à l'emploi en mélangeant des agrégats, du ciment, de l'eau et éventuellement des adjuvants. Le béton est fabriqué selon des spécifications précises pour répondre aux besoins des clients.",
      li2: "",
      titre2: "Coulage de béton ",
      li4: "Les entreprises de béton peuvent également s'occuper du coulage de béton sur le chantier, que ce soit pour des dalles, des fondations, des murs, des planchers, des trottoirs, des routes, etc.",
      li5: "",
      li6: "",
      titre3: "Projets de construction ",
      li7: "Certaines entreprises de béton sont également impliquées dans des projets de construction complets, notamment la conception, la planification et la réalisation de structures en béton telles que des bâtiments, des ponts, des barrages, des digues, des ouvrages de génie civil, etc.",
      li8: "",
      li9: "",
      text: "Il est essentiel de choisir une entreprise de béton expérimentée et réputée pour s'assurer que les travaux de construction ou de rénovation sont réalisés avec succès. Les clients doivent également s'assurer que l'entreprise dispose des équipements nécessaires et qu'elle est couverte par une assurance pour tout dommage potentiel."
    },
    {
      name: "Installations",
      slug: 'Toitures et installations',
      category: 'Travaux',
      image: '/images/gouttiere.jpg',
      image2: '/images/gouttiere.jpg',
      price: 90,
      brand: 'Installations',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Une entreprise de toitures et installations, souvent appelée une entreprise de toitures et d'installations, est spécialisée dans la fourniture de services liés à la toiture ainsi qu'à l'installation de divers équipements ou systèmes sur les toits des bâtiments. Voici un aperçu des services que ce type d'entreprise peut offrir :",
      titre1: "Services de toiture",
      li1: "Réparation de toiture : Réparation des dommages, des fuites et de l'usure de la toiture.",
      li2: "Remplacement de toiture : Installation de nouvelles toitures pour remplacer les anciennes ou endommagées.",
      lib3: "Inspection de toiture : Évaluation de l'état de la toiture pour identifier les problèmes potentiels.",
      titre2: "Services d'installation sur toiture ",
      li4: "Installation de panneaux solaires : Montage de panneaux solaires pour produire de l'énergie solaire.",
      li5: "Installation de systèmes de ventilation : Mise en place de systèmes de ventilation pour améliorer la qualité de l'air intérieur et réguler la température.",
      li6: "Installation de systèmes de refroidissement ou de chauffage : Installation de systèmes de climatisation, de pompes à chaleur, de systèmes de chauffage radiants, etc.",
      titre3: "Services connexes",
      li7: "Étanchéité de toiture : Application de matériaux d'étanchéité pour prévenir les infiltrations d'eau.",
      li8: "Isolation de toiture : Amélioration de l'isolation thermique de la toiture pour réduire la consommation d'énergie.",
      li9: "Installation de fenêtres de toit : Pose de lucarnes ou de fenêtres de toit pour améliorer l'éclairage naturel.",
      text: "Il est essentiel de choisir une entreprise qualifiée et expérimentée pour effectuer des travaux de toiture et d'installation sur votre bâtiment. Avant de prendre une décision, n'hésitez pas à comparer plusieurs entreprises, à vérifier leurs références et à demander des recommandations pour vous assurer de choisir la meilleure entreprise pour votre projet."
    },
    {
      name: "Rénovations",
      slug: 'Toitures et rénovations',
      category: 'Travaux',
      image: '/images/renovation1.jpeg',
      image2: '/images/rénovation2.jpeg',
      price: 90,
      brand: 'Rénovations',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Une entreprise de toitures et de rénovations est spécialisée dans la réparation, la rénovation et la construction de toitures, ainsi que dans la réalisation de projets de rénovation pour les bâtiments. Voici quelques informations essentielles sur ce type d'entreprise :",
      titre1: "Services de toiture",
      li1: "Réparation de toiture : Cela inclut la réparation de fuites, de dommages causés par les intempéries, de problèmes d'isolation, etc.",
      li2: "Remplacement de toiture : Lorsque la toiture est trop endommagée pour être réparée, l'entreprise peut la remplacer par une nouvelle toiture.",
      titre2: "Services de rénovations",
      li4: "Rénovation de bâtiments : Cela peut impliquer la rénovation de l'intérieur et de l'extérieur de bâtiments résidentiels ou commerciaux.",
      li5: "Travaux de rénovation générale : Cela comprend la rénovation de cuisines, de salles de bains, de sous-sols, l'ajout de nouvelles pièces, la rénovation de façades, etc.",
      li6: "",
      titre3: "Services connexes",
      li7: "Inspection de toiture : Avant de commencer des travaux de rénovation ou de réparation de toiture, une inspection est souvent nécessaire pour évaluer l'état de la toiture.",
      li8: "Installation de revêtements de toit : Les entreprises de toitures peuvent installer différents types de revêtements de toit, tels que l'ardoise, le bardeau, le métal, etc.",
      li9: "Travaux de charpente : Les réparations de charpente peuvent être nécessaires lorsque la structure de la toiture est endommagée.",
      text: "Il est important de choisir une entreprise de toitures et de rénovations réputée et expérimentée pour garantir la qualité du travail effectué sur votre propriété. Vous pouvez rechercher des avis, demander des recommandations, et obtenir plusieurs devis pour comparer les offres avant de prendre une décision."
    }
  ],
};

export default data;
